In [35]:
import pandas as pd
import numpy as np

## 3.1 Machine Learning for Classification problems

In [137]:
df = pd.read_csv("data/churn_data/churndata.csv")

## 3.2 Data cleaning

In [138]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [133]:
df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [140]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [141]:
df.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [142]:
df.totalcharges = df.totalcharges.str.replace(" ", "")

In [143]:
df.totalcharges = pd.to_numeric(df.totalcharges)

In [144]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges        float64
churn                   str
dtype: object

In [145]:
#normalizing str column data

str_col = df.dtypes[df.dtypes == "str"].index

In [146]:
str_col

Index(['customerid', 'gender', 'partner', 'dependents', 'phoneservice',
       'multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup',
       'deviceprotection', 'techsupport', 'streamingtv', 'streamingmovies',
       'contract', 'paperlessbilling', 'paymentmethod', 'churn'],
      dtype='str')

In [147]:
for col in str_col:
    df[col] = df[col].str.lower().str.replace(" ", "_")

In [148]:
df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,yes,electronic_check,29.85,29.85,no
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,one_year,no,mailed_check,56.95,1889.50,no
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailed_check,53.85,108.15,yes
3,7795-cfocw,male,0,no,no,45,no,no_phone_service,dsl,yes,...,yes,yes,no,no,one_year,no,bank_transfer_(automatic),42.30,1840.75,no
4,9237-hqitu,female,0,no,no,2,yes,no,fiber_optic,no,...,no,no,no,no,month-to-month,yes,electronic_check,70.70,151.65,yes

In [48]:
df.churn = (df.churn == "yes").astype(int)

In [49]:
df.churn

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: churn, Length: 7043, dtype: int64

## 3.3 Setting up validation framework

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
df_full_train = df

In [76]:
df_full_train.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,yes,electronic_check,29.85,29.85,0
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,one_year,no,mailed_check,56.95,1889.50,0
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailed_check,53.85,108.15,1
3,7795-cfocw,male,0,no,no,45,no,no_phone_service,dsl,yes,...,yes,yes,no,no,one_year,no,bank_transfer_(automatic),42.30,1840.75,0
4,9237-hqitu,female,0,no,no,2,yes,no,fiber_optic,no,...,no,no,no,no,month-to-month,yes,electronic_check,70.70,151.65,1

In [77]:
df_train, df_test = train_test_split(df_full_train, test_size=0.4, random_state=1)

In [78]:
df_train.shape, df_test.shape

((4225, 21), (2818, 21))

In [79]:
df_test, df_val = train_test_split(df_test, test_size=0.5, random_state=1)

In [80]:
df_test.shape, df_val.shape

((1409, 21), (1409, 21))

In [81]:
df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)

In [86]:
y_train.shape, y_val.shape, y_test.shape

((4225,), (1409,), (1409,))

In [83]:
y_train = df_train.churn.values
y_test = df_test.churn.values
y_val = df_val.churn.values

In [84]:
del df_train["churn"]
del df_test["churn"]
del df_val["churn"]

In [88]:
df_test.shape

(1409, 20)

In [89]:
df_full_train.isnull().sum()

customerid           0
gender               0
seniorcitizen        0
partner              0
dependents           0
tenure               0
phoneservice         0
multiplelines        0
internetservice      0
onlinesecurity       0
onlinebackup         0
deviceprotection     0
techsupport          0
streamingtv          0
streamingmovies      0
contract             0
paperlessbilling     0
paymentmethod        0
monthlycharges       0
totalcharges        11
churn                0
dtype: int64

In [94]:
df_train = df_train.fillna(0)
df_test = df_test.fillna(0)
df_val = df_val.fillna(0)

In [96]:
df_val.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
dtype: int64

## 3.4 EDA

In [99]:
df_full_train.churn.value_counts(normalize=True)

churn
0    0.73463
1    0.26537
Name: proportion, dtype: float64

In [100]:
df_full_train.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges        float64
churn                 int64
dtype: object

In [101]:
numerical_column = ["tenure", "monthlycharges", "totalcharges"]

In [102]:
categorical = [
    'gender',
    'seniorcitizen',
    'partner',
    'dependents',
    'phoneservice',
    'multiplelines',
    'internetservice',
    'onlinesecurity',
    'onlinebackup',
    'deviceprotection',
    'techsupport',
    'streamingtv',
    'streamingmovies',
    'contract',
    'paperlessbilling',
    'paymentmethod',
]

In [111]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

## 3.5 Feature Importance: Churn Rate and Risk Ratio

In [112]:
df_full_train.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,yes,electronic_check,29.85,29.85,0
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,one_year,no,mailed_check,56.95,1889.50,0
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailed_check,53.85,108.15,1
3,7795-cfocw,male,0,no,no,45,no,no_phone_service,dsl,yes,...,yes,yes,no,no,one_year,no,bank_transfer_(automatic),42.30,1840.75,0
4,9237-hqitu,female,0,no,no,2,yes,no,fiber_optic,no,...,no,no,no,no,month-to-month,yes,electronic_check,70.70,151.65,1

In [120]:
churn_female = df_full_train[(df_full_train.gender == "female")].churn.mean()
churn_female

np.float64(0.26920871559633025)

In [122]:
churn_male = df_full_train[(df_full_train.gender == "male")].churn.mean()
churn_male

np.float64(0.2616033755274262)

In [119]:
global_churn_rate = df_full_train.churn.mean()
global_churn_rate

np.float64(0.2653698707936959)

In [150]:
df_full_train.partner.value_counts()

partner
no     3641
yes    3402
Name: count, dtype: int64

In [126]:
churn_yes_partner = df_full_train[df_full_train.partner == "yes"].churn.mean()
churn_yes_partner

np.float64(0.1966490299823633)

In [127]:
churn_no_partner = df_full_train[df_full_train.partner == "no"].churn.mean()
churn_no_partner

np.float64(0.32957978577313923)

In [128]:
global_churn_rate - churn_no_partner

np.float64(-0.06420991497944334)

In [129]:
global_churn_rate - churn_yes_partner

np.float64(0.06872084081133259)

### Risk Ratio

In [151]:
churn_no_partner/global_churn_rate

np.float64(1.241963847619165)

In [152]:
churn_yes_partner/global_churn_rate

np.float64(0.7410375164075894)

In [ ]:
from IPython.display import display

In [155]:
for c in categorical:
    df_group = df_full_train.groupby(c).churn.agg(["mean", "count"])
    df_group["diff"] = df_group["mean"] - global_churn_rate
    df_group["risk/raito"] = df_group["mean"] / global_churn_rate
    display(df_group)
    print()

            mean  count      diff  risk/raito
gender
female  0.269209   3488  0.003839    1.014466
male    0.261603   3555 -0.003766    0.985807

                   mean  count      diff  risk/raito
seniorcitizen
0              0.236062   5901 -0.029308    0.889557
1              0.416813   1142  0.151443    1.570686

             mean  count      diff  risk/raito
partner
no       0.329580   3641  0.064210    1.241964
yes      0.196649   3402 -0.068721    0.741038

                mean  count      diff  risk/raito
dependents
no          0.312791   4933  0.047422    1.178700
yes         0.154502   2110 -0.110868    0.582215

                  mean  count      diff  risk/raito
phoneservice
no            0.249267    682 -0.016103    0.939319
yes           0.267096   6361  0.001726    1.006506

                      mean  count      diff  risk/raito
multiplelines
no                0.250442   3390 -0.014927    0.943749
no_phone_service  0.249267    682 -0.016103    0.939319
yes               0.286099   2971  0.020729    1.078114

                     mean  count      diff  risk/raito
internetservice
dsl              0.189591   2421 -0.075779    0.714441
fiber_optic      0.418928   3096  0.153558    1.578656
no               0.074050   1526 -0.191320    0.279044

                         mean  count      diff  risk/raito
onlinesecurity
no                   0.417667   3498  0.152297    1.573906
no_internet_service  0.074050   1526 -0.191320    0.279044
yes                  0.146112   2019 -0.119258    0.550597

                         mean  count      diff  risk/raito
onlinebackup
no                   0.399288   3088  0.133918    1.504645
no_internet_service  0.074050   1526 -0.191320    0.279044
yes                  0.215315   2429 -0.050055    0.811377

                         mean  count      diff  risk/raito
deviceprotection
no                   0.391276   3095  0.125906    1.474456
no_internet_service  0.074050   1526 -0.191320    0.279044
yes                  0.225021   2422 -0.040349    0.847951

                         mean  count      diff  risk/raito
techsupport
no                   0.416355   3473  0.150985    1.568960
no_internet_service  0.074050   1526 -0.191320    0.279044
yes                  0.151663   2044 -0.113706    0.571517

                         mean  count      diff  risk/raito
streamingtv
no                   0.335231   2810  0.069861    1.263261
no_internet_service  0.074050   1526 -0.191320    0.279044
yes                  0.300702   2707  0.035332    1.133143

                         mean  count      diff  risk/raito
streamingmovies
no                   0.336804   2785  0.071434    1.269188
no_internet_service  0.074050   1526 -0.191320    0.279044
yes                  0.299414   2732  0.034044    1.128291

                    mean  count      diff  risk/raito
contract
month-to-month  0.427097   3875  0.161727    1.609440
one_year        0.112695   1473 -0.152675    0.424672
two_year        0.028319   1695 -0.237051    0.106714

                      mean  count      diff  risk/raito
paperlessbilling
no                0.163301   2872 -0.102069    0.615371
yes               0.335651   4171  0.070281    1.264842

                               mean  count      diff  risk/raito
paymentmethod
bank_transfer_(automatic)  0.167098   1544 -0.098271    0.629681
credit_card_(automatic)    0.152431   1522 -0.112939    0.574410
electronic_check           0.452854   2365  0.187484    1.706502
mailed_check               0.191067   1612 -0.074303    0.720003

## 3.6 Feature importance: Mutual information

In [156]:
from sklearn.metrics import mutual_info_score

In [157]:
mutual_info_score(df_full_train.churn, df_full_train.gender)

3.7082914405128786e-05

In [158]:
mutual_info_score(df_full_train.techsupport, df_full_train.churn)

0.06302103606897548

In [159]:
mutual_info_score(df_full_train.contract, df_full_train.churn)

0.09845305342598942

In [160]:
def mutual_info_score_fun(series):
    return mutual_info_score(series, df_full_train.churn)

In [162]:
mi = df_full_train[categorical].apply(mutual_info_score_fun)
mi.sort_values(ascending=False)

contract            0.098453
onlinesecurity      0.064677
techsupport         0.063021
internetservice     0.055574
onlinebackup        0.046792
paymentmethod       0.044519
deviceprotection    0.043917
streamingmovies     0.032001
streamingtv         0.031908
paperlessbilling    0.019194
dependents          0.014467
partner             0.011454
seniorcitizen       0.010577
multiplelines       0.000801
phoneservice        0.000072
gender              0.000037
dtype: float64

## 3.7 Feature Importance: Correlation

In [164]:
df_full_train.tenure.max()

np.int64(72)

In [165]:
df_full_train[numerical_column].corrwith(df_full_train.churn)

tenure           -0.352229
monthlycharges    0.193356
totalcharges     -0.199484
dtype: float64

In [167]:
df_full_train[(df_full_train.tenure <2)].churn.mean()

np.float64(0.6089743589743589)

In [171]:
df_full_train[(df_full_train.tenure > 2) & (df_full_train.tenure <= 12)].churn.mean()

np.float64(0.4033232628398791)

In [170]:
df_full_train[df_full_train.tenure > 12].churn.mean()

np.float64(0.17129915585752523)

## 3.8 One Hot Encoding

In [173]:
from sklearn.feature_extraction import DictVectorizer

In [184]:
dv = DictVectorizer(sparse=False)

In [185]:
dict_train = df_train[categorical + numerical_column].to_dict(orient="records")

In [186]:
dv.fit(dict_train)
X_train = dv.transform(dict_train)

In [189]:
val_dict = df_val[categorical + numerical_column].to_dict(orient="records")
X_val = dv.transform(val_dict)

## 3.9 Training logistic regression model

In [191]:
from sklearn.linear_model import LogisticRegression

In [193]:
model = LogisticRegression()
model.fit(X_train, y_train)

C:\Users\sonud\AppData\Local\Python\pythoncore-3.13-64\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [197]:
model.intercept_

array([-0.11784034])

In [200]:
model.coef_.round(2)

array([[ 0.25, -0.15, -0.22,  0.05, -0.17,  0.08, -0.08, -0.12, -0.06,
        -0.06, -0.3 ,  0.26, -0.08,  0.  , -0.22,  0.03,  0.07,  0.06,
        -0.08, -0.1 ,  0.23, -0.08, -0.27, -0.28,  0.16, -0.05, -0.07,
        -0.1 , -0.09,  0.28, -0.2 ,  0.03, -0.15,  0.21, -0.08, -0.08,
         0.04, -0.1 , -0.08,  0.06,  0.25, -0.08, -0.28, -0.07,  0.  ]])

In [206]:
y_pred = model.predict(X_train)

In [208]:
acc = (y_pred == y_train).mean()

In [209]:
acc

np.float64(0.8044970414201184)